services:
  postgres:
    image: postgres:14.4
    container_name: ses-mgr-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ses_mgr
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: