spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/ses_mgr_test
    username: postgres_test
    password: postgres_test
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  thymeleaf:
    cache: false

# テスト環境固有の設定
logging:
  level:
    root: WARN
    jp.co.example.sesapp: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.data.jdbc: DEBUG
    org.flywaydb: DEBUG

# アプリケーション固有の設定
application:
  security:
    jwt:
      secret-key: test-secret-key
      token-validity-in-seconds: 86400
      refresh-token-expiration: 604800000 # 7日間
    account:
      max-failed-attempts: 5
  logging:
    request-response: true
  storage:
    type: minio
    minio:
      endpoint: http://localhost:9010
      access-key: miniotest
      secret-key: miniotest
      bucket: ses-mgr-test