spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ses_mgr_dev
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

# 開発環境固有の設定
logging:
  level:
    jp.co.example.sesapp: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.data.jdbc: DEBUG

# アプリケーション固有の設定
application:
  security:
    jwt:
      token-validity-in-seconds: 86400
  logging:
    request-response: true
  storage:
    minio:
      url: http://localhost:9000
      access-key: minioadmin
      secret-key: minioadmin
      bucket: sesmgr-dev