spring:
  application:
    name: ses-mgr
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ses_mgr
    username: postgres
    password: postgres
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:}
            client-secret: ${GOOGLE_CLIENT_SECRET:}
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

server:
  port: 8080
  servlet:
    context-path: /
  error:
    include-stacktrace: never

# アプリケーション固有の設定
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET:defaultsecretkey}
      token-validity-in-seconds: 86400
  logging:
    request-response: ${ENABLE_REQUEST_RESPONSE_LOGGING:false}

# アクチュエータの設定
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

# ロギング設定
logging:
  level:
    root: INFO
    jp.co.example.sesapp: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.data.jdbc: INFO