spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ses_mgr}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  thymeleaf:
    cache: true
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

# 本番環境固有の設定
logging:
  level:
    root: WARN
    jp.co.example.sesapp: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN

# アプリケーション固有の設定
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      token-validity-in-seconds: ${JWT_VALIDITY:86400}
  logging:
    request-response: false

server:
  tomcat:
    max-threads: 200
    min-spare-threads: 20