package jp.co.example.sesapp.common.auth.domain;

/**
 * 認証イベント種別の列挙型。
 */
public enum AuthEventType {
    LOGIN_ATTEMPT,
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    LOGIN_FAILED,
    LOGOUT,
    PASSWORD_RESET_REQUEST,
    PASSWORD_RESET_SUCCESS,
    PASSWORD_CHANGE,
    MFA_ENABLED,
    MFA_DISABLED,
    MFA_VERIFICATION_SUCCESS,
    MFA_VERIFICATION_FAILURE,
    ACCOUNT_LOCKED,
    ACCOUNT_UNLOCKED,
    TOKEN_REFRESH,
    TOKEN_REFRESH_FAILED,
    TOKEN_EXPIRED,
    ACCOUNT_DISABLED,
    ACCOUNT_EXPIRED,
    CREDENTIALS_EXPIRED,
    MFA_FAILED,
    MFA_SETUP_FAILED,
    MFA_DISABLE_FAILED,
    PASSWORD_CHANGE_FAILED,
    PASSWORD_RESET_FAILED,
    UNAUTHORIZED
}