openapi: 3.0.3
info:
  title: SES業務システム API
  description: |
    SES業務システムのREST API仕様書です。
    このファイルは、各機能領域のAPI仕様を統合したものです。
  version: 1.0.0

# 共通の定義をインポート
servers:
  - url: https://api.example.com/api/v1
    description: 本番環境
  - url: https://staging-api.example.com/api/v1
    description: ステージング環境
  - url: https://dev-api.example.com/api/v1
    description: 開発環境

# 各API定義ファイルへの参照
paths:
  # 認証API
  /auth/login:
    $ref: './auth.yaml#/paths/~1auth~1login'
  /auth/logout:
    $ref: './auth.yaml#/paths/~1auth~1logout'
  /auth/refresh-token:
    $ref: './auth.yaml#/paths/~1auth~1refresh-token'
  /auth/profile:
    $ref: './auth.yaml#/paths/~1auth~1profile'
  /auth/password:
    $ref: './auth.yaml#/paths/~1auth~1password'
  /auth/password/reset-request:
    $ref: './auth.yaml#/paths/~1auth~1password~1reset-request'
  /auth/password/reset:
    $ref: './auth.yaml#/paths/~1auth~1password~1reset'

  # 案件管理API
  /projects:
    $ref: './projects.yaml#/paths/~1projects'
  /projects/{id}:
    $ref: './projects.yaml#/paths/~1projects~1{id}'
    
  # 技術者管理API
  /engineers:
    $ref: './engineers.yaml#/paths/~1engineers'
  /engineers/{engineer_id}:
    $ref: './engineers.yaml#/paths/~1engineers~1{engineer_id}'
  /engineers/{engineer_id}/status:
    $ref: './engineers.yaml#/paths/~1engineers~1{engineer_id}~1status'
  /engineers/{engineer_id}/documents:
    $ref: './engineers.yaml#/paths/~1engineers~1{engineer_id}~1documents'
  /engineers/{engineer_id}/documents/{document_id}:
    $ref: './engineers.yaml#/paths/~1engineers~1{engineer_id}~1documents~1{document_id}'
  /engineers/{engineer_id}/work-status:
    $ref: './engineers.yaml#/paths/~1engineers~1{engineer_id}~1work-status'
  /engineers/{engineer_id}/skills:
    $ref: './engineers.yaml#/paths/~1engineers~1{engineer_id}~1skills'
  /engineers/{engineer_id}/skills/{skill_id}:
    $ref: './engineers.yaml#/paths/~1engineers~1{engineer_id}~1skills~1{skill_id}'
  /engineers/search:
    $ref: './engineers.yaml#/paths/~1engineers~1search'
  /engineers/search/skills:
    $ref: './engineers.yaml#/paths/~1engineers~1search~1skills'
  /engineers/search/availability:
    $ref: './engineers.yaml#/paths/~1engineers~1search~1availability'
  /engineers/search/quick:
    $ref: './engineers.yaml#/paths/~1engineers~1search~1quick'
    
  # スキル管理API
  /skills:
    $ref: './engineers.yaml#/paths/~1skills'
  /skills/categories:
    $ref: './engineers.yaml#/paths/~1skills~1categories'
  /skills/{skill_id}:
    $ref: './engineers.yaml#/paths/~1skills~1{skill_id}'
  /skills/categories/{category_id}:
    $ref: './engineers.yaml#/paths/~1skills~1categories~1{category_id}'
    
  # マッチング機能API
  /matching/search:
    $ref: './matching.yaml#/paths/~1matching~1search'
  /matching/results:
    $ref: './matching.yaml#/paths/~1matching~1results'
  /matching/results/{result_id}:
    $ref: './matching.yaml#/paths/~1matching~1results~1{result_id}'
  /proposals:
    $ref: './matching.yaml#/paths/~1proposals'
  /proposals/{proposal_id}:
    $ref: './matching.yaml#/paths/~1proposals~1{proposal_id}'
  /proposals/{proposal_id}/status:
    $ref: './matching.yaml#/paths/~1proposals~1{proposal_id}~1status'
  /proposal-documents:
    $ref: './matching.yaml#/paths/~1proposal-documents'
  /proposal-documents/{document_id}:
    $ref: './matching.yaml#/paths/~1proposal-documents~1{document_id}'
  /proposal-documents/{document_id}/status:
    $ref: './matching.yaml#/paths/~1proposal-documents~1{document_id}~1status'
  /proposal-documents/{document_id}/download:
    $ref: './matching.yaml#/paths/~1proposal-documents~1{document_id}~1download'
    
  # 契約管理API
  /contracts:
    $ref: './contracts.yaml#/paths/~1contracts'
  /contracts/{contract_id}:
    $ref: './contracts.yaml#/paths/~1contracts~1{contract_id}'
  /contracts/{contract_id}/status:
    $ref: './contracts.yaml#/paths/~1contracts~1{contract_id}~1status'
  /contract-documents:
    $ref: './contracts.yaml#/paths/~1contract-documents'
  /contract-documents/{document_id}:
    $ref: './contracts.yaml#/paths/~1contract-documents~1{document_id}'
  /contract-documents/{document_id}/download:
    $ref: './contracts.yaml#/paths/~1contract-documents~1{document_id}~1download'
  /contract-templates:
    $ref: './contracts.yaml#/paths/~1contract-templates'
  /contract-templates/{template_id}:
    $ref: './contracts.yaml#/paths/~1contract-templates~1{template_id}'
  /contract-templates/{template_id}/preview:
    $ref: './contracts.yaml#/paths/~1contract-templates~1{template_id}~1preview'
  /signatures:
    $ref: './contracts.yaml#/paths/~1signatures'
  /signatures/{signature_id}:
    $ref: './contracts.yaml#/paths/~1signatures~1{signature_id}'
  /signatures/{signature_id}/resend:
    $ref: './contracts.yaml#/paths/~1signatures~1{signature_id}~1resend'
  /signatures/{signature_id}/sign:
    $ref: './contracts.yaml#/paths/~1signatures~1{signature_id}~1sign'

  # 勤怠工数管理API
  /timesheets:
    $ref: './timesheet.yaml#/paths/~1timesheets'
  /timesheets/{timesheet_id}:
    $ref: './timesheet.yaml#/paths/~1timesheets~1{timesheet_id}'
  /timesheets/{timesheet_id}/entries:
    $ref: './timesheet.yaml#/paths/~1timesheets~1{timesheet_id}~1entries'
  /timesheets/{timesheet_id}/entries/{entry_id}:
    $ref: './timesheet.yaml#/paths/~1timesheets~1{timesheet_id}~1entries~1{entry_id}'
  /timesheets/{timesheet_id}/submit:
    $ref: './timesheet.yaml#/paths/~1timesheets~1{timesheet_id}~1submit'
  /timesheets/{timesheet_id}/approve:
    $ref: './timesheet.yaml#/paths/~1timesheets~1{timesheet_id}~1approve'
  /timesheets/{timesheet_id}/reject:
    $ref: './timesheet.yaml#/paths/~1timesheets~1{timesheet_id}~1reject'
  /workitem-records:
    $ref: './timesheet.yaml#/paths/~1workitem-records'
  /workitem-records/{record_id}:
    $ref: './timesheet.yaml#/paths/~1workitem-records~1{record_id}'
  /workitem-records/{record_id}/items:
    $ref: './timesheet.yaml#/paths/~1workitem-records~1{record_id}~1items'
  /workitem-records/{record_id}/items/{item_id}:
    $ref: './timesheet.yaml#/paths/~1workitem-records~1{record_id}~1items~1{item_id}'
  /workitem-records/{record_id}/submit:
    $ref: './timesheet.yaml#/paths/~1workitem-records~1{record_id}~1submit'
  /workitem-records/{record_id}/approve:
    $ref: './timesheet.yaml#/paths/~1workitem-records~1{record_id}~1approve'
  /workitem-records/{record_id}/reject:
    $ref: './timesheet.yaml#/paths/~1workitem-records~1{record_id}~1reject'
  /reports/timesheet:
    $ref: './timesheet.yaml#/paths/~1reports~1timesheet'
  /reports/workitem:
    $ref: './timesheet.yaml#/paths/~1reports~1workitem'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT形式のアクセストークンを使用した認証

tags:
  - name: auth
    description: 認証関連のAPI
  - name: projects
    description: 案件管理API
  - name: engineers
    description: 技術者管理API
  - name: skills
    description: スキル管理API
  - name: matching
    description: マッチング検索API
  - name: proposals
    description: 提案管理API
  - name: proposal-documents
    description: 提案書管理API
  - name: contracts
    description: 契約基本API
  - name: contract-documents
    description: 契約書ドキュメントAPI
  - name: contract-templates
    description: 契約テンプレートAPI
  - name: signatures
    description: 電子署名API
  - name: timesheet
    description: 勤怠管理API
  - name: timesheet-entries
    description: 勤怠エントリAPI
  - name: workitem-records
    description: 工数記録API
  - name: workitem-items
    description: 工数項目API
  - name: timesheet-reports
    description: 勤怠集計レポートAPI
  - name: workitem-reports
    description: 工数集計レポートAPI
  - name: billing
    description: 請求・支払管理API
  - name: reports
    description: レポーティングAPI
  - name: admin
    description: システム管理API